import type { Metadata } from "next";

import "@/src/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <h1>admin header</h1>
        {children}
        <h1>admin footer</h1>
      </body>
    </html>
  );
}
